### ISSUE TITLE
Joe Contracts can't be verified

### ISSUE THREAD

**Issue by timbotro** [Snowball-Finance/protocol#89]
## Description
I've gone through the Joe strategy and snowglobe contracts and the following aren't verifiable with the repo's hardhat contracts.
The deployer addresses in context are:
- 0xc9a51fB9057380494262fd291aED74317332C0a2
- 0xdbc195a0ED72c0B059f8906e97a90636d2B6409F

The owners of this address, or the person who deployed these contracts, should check their settings or state what compiler and optimiser settings they used. Not being able to verify our contracts makes it hard for both our users and ourselves to troubleshoot issues

## Affected Contracts
	• Strategy joe-avax-ethe
		○ https://cchain.explorer.avax.network/address/0xF3c9D8f8F2784e63BD2631c4a4c6Ef02973Aa6F2/transactions
	• Strategy joe-avax-daie
		○ https://cchain.explorer.avax.network/address/0x66f37F73FaC11f4012dD2e9D2844B386212C1961/transactions
	• Strategy joe-avax-shibx
		○ https://cchain.explorer.avax.network/address/0x0f30223798499EF8A0825229abA9353537108F80/transactions
	• StrategyJoeAvaxMimLp
		○ https://cchain.explorer.avax.network/address/0xAFCa35AE5Dd4D8FC900AD7b08d7f3e96E498B2B8/transactions
	• StrategyJoeAvaxTimeLp
		○ https://cchain.explorer.avax.network/address/0xc42701aE4bacF65A23B82abd42E549aab4fCC2EB/transactions
	• StrategyJoeAvaxFraxLp
		○ https://cchain.explorer.avax.network/address/0x55864D8f42452b3AFEF83B4831E3253581bEe080/transactions
	• StrategyJoeAvaxSynLp
		○ https://cchain.explorer.avax.network/address/0xc79E3F17b88E7E621196cc2d5A6B23617dC62ED9/transactions
	• StrategyJoeAvaxEleLp
		○ https://cchain.explorer.avax.network/address/0x9185D1f86592DC670568B240c7cc5bFF7a04DC4d/transactions
	• StrategyJoeUsdceJoeLp
		○ https://cchain.explorer.avax.network/address/0x043a2eCE3C99fcBCB879A469c35BF267Bf842D4C/transactions
	• StrategyJoeMaiUsdce
		○ https://cchain.explorer.avax.network/address/0xcb0A11DfA23e457A917488f11843822085edf146/transactions
	• StrategyJoeAvaxBifi
		○ https://cchain.explorer.avax.network/address/0x96e751710e88c867A9449e4eb97C65b9ea2D6cCb/transactions
	• StrategyJoeAvaxAavee
		○ https://cchain.explorer.avax.network/address/0xc487FD871031ba788aEa388557Ceb2C0E8BFeACd/contracts
	• StrategyJoeAvaxMai
		○ https://cchain.explorer.avax.network/address/0xBe7527A9CB26E62B7E9F1850f8141F289682f665/transactions
	• StrategyJoeUsdceJoe
		○ https://cchain.explorer.avax.network/address/0x043a2eCE3C99fcBCB879A469c35BF267Bf842D4C/transactions
	• StrategyJoeAvaxWet
		○ https://cchain.explorer.avax.network/address/0x04249D6B55769f69e8E810e60ae885AD75646306/contracts
	• StrategyJoeAvaxEle
		○ https://cchain.explorer.avax.network/address/0x9185D1f86592DC670568B240c7cc5bFF7a04DC4d/contracts
	• StrategyJoeUsdteUsdce
		○ https://cchain.explorer.avax.network/address/0xF6AaAb65b735e71951Af436bBa7aC4461c9E3E83/contracts

**Comment by fuzzylemma** [comment]
@bigwampa @jomarip are these deprecated strategies? if so this should be closed.

**Comment by jomarip** [comment]
I think Avax-Daie is live, but yeah, I think this is stale and can be closed.
